version: "3.9"
networks:
  scala:
    driver: bridge
services:
  nginx:
    build: ./deploy
    networks:
      - scala
    ports:
      - "3000:3000"
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
  frontend:
    container_name: scala_frontend
    build: ./frontend
    networks:
      - scala
  backend:
    container_name: scala_backend
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - scala
